version: '3.8'

services:
  rag-ui:
    # Собираем образ из Dockerfile в текущей директории
    build: .
    # Даем контейнеру имя для удобства
    container_name: rag_ui_service
    # Перезапускать контейнер автоматически в случае сбоя
    restart: unless-stopped
    # Пробрасываем порт 7860 с хоста в контейнер
    ports:
      - "7860:7860"
    # Добавляем переменную окружения NO_PROXY
    environment:
      - NO_PROXY=192.168.42.188,192.168.45.55,192.168.45.79
