version: '3.8'

services:
  rag-ui:
    # Указываем Docker собирать образ из Dockerfile в текущей директории
    build: .
    # Даем контейнеру имя для удобства
    container_name: rag_ui_service
    # Пробрасываем порт 80 хоста на порт 7860 контейнера.
    # Ваш сервис будет доступен по http://<IP_DEBIAN_VM>:80
    ports:
      - "7860:7860"
    # Перезапускать контейнер автоматически в случае сбоя
    restart: unless-stopped
    networks:
      - rag-net

# --- ДОБАВЛЕНО: Описываем, что rag-net это внешняя сеть ---
networks:
  rag-net:
    external: true
